version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "benreceveur"
    assignees:
      - "benreceveur"
    labels:
      - "dependencies"
      - "automated"
    # Group minor and patch updates together
    groups:
      development-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Enable security updates for Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "benreceveur"
    labels:
      - "dependencies"
      - "python"
      - "security"

  # Monitor GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
